#!/bin/sh
NOCACHE_PATH=$(dirname "$0")
libnocache="$NOCACHE_PATH/nocache.so"

export LD_PRELOAD="$libnocache $LD_PRELOAD"

BIN_NAME=$(basename "$0")
if [ "$BIN_NAME" != "nocache" ]; then
    PROG=`which -a "$BIN_NAME" | grep -vF "$0"`
else
    if [ "$1" = "-n" ]; then
	export NOCACHE_NR_FADVISE="$2"
	shift 2
    fi
    PROG="$1"
    shift
fi

exec "$PROG" "$@"
